Repository Team-JUST/Virex, pull requests merged in 2025-09, with the labels that each got.

#27 [FIX][#26]: Recovery.jsx 중복 트리거로 인한 main.py 중복 실행 수정
  src/pages/Recovery.jsx
Labels: FIX

#28 [FEAT][#19]: 파일 개별 다운로드 구현 + 속도 개선(GPU 사용) + 충돌 수정
  index.html
  main.js
  package-lock.json
  package.json
  preload.js
  python_engine/core/image_loader/e01_parser.py
  python_engine/core/recovery/mp4/extract_slack.py
  python_engine/core/recovery/utils/ffmpeg_wrapper.py
  python_engine/main.py
  src/images/recoveryPauseIcon.svg
  src/pages/Recovery.jsx
  src/styles/Recovery.css
Labels: ENHANCE, FEAT, FIX

#33 [FEAT][#29]: Session 기능 추가
  package-lock.json
  package.json
  src/images/resetIcon.svg
  src/pages/Recovery.jsx
  src/session.js
Labels: ENHANCE, FEAT

#42 [FEAT][#41]: 단일 영상 파일(MP4, AVI, JDR) 파서 분리 및 지원
  python_engine/core/analyzer/basic_info_parser.py
  python_engine/core/image_loader/single_video_parser.py
  python_engine/core/recovery/avi/extract_slack.py
  python_engine/core/recovery/mp4/extract_slack.py
  python_engine/main.py
Labels: FEAT

#59 [FEAT][#35]: AVI/MP4 오디오 추출 기능 추가
  python_engine/core/recovery/avi/avi_split_channel.py
  python_engine/core/recovery/avi/extract_slack.py
  python_engine/core/recovery/avi/recover_audio.py
  python_engine/core/recovery/mp4/extract_audio.py
  python_engine/core/recovery/mp4/extract_slack.py
  python_engine/core/recovery/mp4/get_slack_after_moov.py
  src/pages/Recovery.jsx
Labels: FEAT

#61 [FEAT][#52]: AVI 손상 복구 시 fallback 로직 추가
  python_engine/core/analyzer/basic_info_parser.py
  python_engine/core/analyzer/integrity.py
  python_engine/core/image_loader/e01_parser.py
  python_engine/core/image_loader/single_video_parser.py
  python_engine/core/recovery/avi/avi_split_channel.py
  python_engine/core/recovery/avi/extract_slack.py
  python_engine/core/recovery/utils/ffmpeg_wrapper.py
Labels: FEAT

#75 [FEAT][#74] JDR integrity 추가
  python_engine/core/analyzer/integrity.py
  python_engine/core/recovery/jdr/extract_jdr.py
Labels: FEAT

#86 [FIX][#85]: Information 페이지 내 Github 주소 제거
  src/pages/Information.jsx
Labels: CHORE
